name:  Tests

on: [push]

jobs:
  run-tests:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
            node-version: 12
      - run: yarn install --pure-lockfile
        name: Install dependencies
      - run: yarn test
        name: Run tests
